/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import java.awt.Font;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Asus
 */
public class AplikasiBukuAlamat extends javax.swing.JFrame {

    /**
     * Creates new form AplikasiBukuAlamat
     */
    public AplikasiBukuAlamat() {
        initComponents();
       
        showDate();
        
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelUtama = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbbukualamat = new javax.swing.JTable();
        tfTelp = new javax.swing.JTextField();
        cmbJenisKelamin = new javax.swing.JComboBox<>();
        cmbStatus = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tfNama = new javax.swing.JTextField();
        tfAlamat = new javax.swing.JTextField();
        bttambah = new javax.swing.JButton();
        bthapus = new javax.swing.JButton();
        btubah = new javax.swing.JButton();
        tbimport = new javax.swing.JButton();
        tbexport = new javax.swing.JButton();
        TextArealaporan = new java.awt.TextArea();
        btlaporan = new java.awt.Button();
        DATE = new javax.swing.JLabel();
        btexit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelUtama.setBackground(new java.awt.Color(51, 255, 0));

        jLabel3.setText("Jenis Kelamin");

        jLabel4.setText("Status");

        jLabel5.setText("No.Telp");

        tbbukualamat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nama", "Alamat", "JenisKelamin", "Status", "NoTelp"
            }
        ));
        tbbukualamat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbbukualamatMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbbukualamat);

        cmbJenisKelamin.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pria", "Perempuan" }));

        cmbStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Keluarga ", "Sendiri", "Teman" }));

        jLabel1.setText("Nama");

        jLabel2.setText("Alamat");

        bttambah.setText("Tambah");
        bttambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttambahActionPerformed(evt);
            }
        });

        bthapus.setText("Hapus");
        bthapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bthapusActionPerformed(evt);
            }
        });

        btubah.setText("Ubah");
        btubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btubahActionPerformed(evt);
            }
        });

        tbimport.setText("import");
        tbimport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbimportActionPerformed(evt);
            }
        });

        tbexport.setText("Export");
        tbexport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbexportActionPerformed(evt);
            }
        });

        btlaporan.setLabel("Laporan");
        btlaporan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btlaporanActionPerformed(evt);
            }
        });

        DATE.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        DATE.setText("DATE");
        DATE.setToolTipText("");

        btexit.setText("EXIT");
        btexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btexitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelUtamaLayout = new javax.swing.GroupLayout(panelUtama);
        panelUtama.setLayout(panelUtamaLayout);
        panelUtamaLayout.setHorizontalGroup(
            panelUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelUtamaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelUtamaLayout.createSequentialGroup()
                        .addGroup(panelUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(44, 44, 44)
                        .addGroup(panelUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelUtamaLayout.createSequentialGroup()
                                .addComponent(cmbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(DATE, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(213, 213, 213))
                            .addGroup(panelUtamaLayout.createSequentialGroup()
                                .addGroup(panelUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cmbJenisKelamin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfTelp, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(623, Short.MAX_VALUE))
                            .addGroup(panelUtamaLayout.createSequentialGroup()
                                .addComponent(tfNama, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btexit)
                                .addGap(36, 36, 36))))
                    .addGroup(panelUtamaLayout.createSequentialGroup()
                        .addGroup(panelUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(panelUtamaLayout.createSequentialGroup()
                        .addGroup(panelUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bttambah)
                            .addComponent(tbimport))
                        .addGap(31, 31, 31)
                        .addGroup(panelUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bthapus)
                            .addComponent(tbexport))
                        .addGap(35, 35, 35)
                        .addGroup(panelUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btubah)
                            .addGroup(panelUtamaLayout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(btlaporan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(TextArealaporan, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24))))
            .addGroup(panelUtamaLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        panelUtamaLayout.setVerticalGroup(
            panelUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelUtamaLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(panelUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btlaporan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelUtamaLayout.createSequentialGroup()
                        .addGroup(panelUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(tfNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btexit))
                        .addGap(18, 18, 18)
                        .addGroup(panelUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(tfAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(panelUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(cmbJenisKelamin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(panelUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelUtamaLayout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addGroup(panelUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(cmbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4))
                                .addGap(18, 18, 18)
                                .addGroup(panelUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(panelUtamaLayout.createSequentialGroup()
                                        .addGroup(panelUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel5)
                                            .addComponent(tfTelp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(40, 40, 40)
                                        .addGroup(panelUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(bttambah)
                                            .addGroup(panelUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(bthapus)
                                                .addComponent(btubah))))
                                    .addComponent(TextArealaporan, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(panelUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tbimport)
                                    .addComponent(tbexport)))
                            .addGroup(panelUtamaLayout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addComponent(DATE)))))
                .addContainerGap(98, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelUtama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(panelUtama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private int selectedRow = -1; // digunakan untuk menyimpan baris yang telah dipilih
    private boolean isEditMode = false; // digunakan saat pengeditan
    
    private void bttambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttambahActionPerformed
     String nama = tfNama.getText();
     String alamat = tfAlamat.getText();
     String jenisKelamin = cmbJenisKelamin.getSelectedItem().toString();
     String status = cmbStatus.getSelectedItem().toString();
     String noTelp = tfTelp.getText();
     
     //Mengecek nilai yang di input
     if (tfNama.getText().equals("") || tfAlamat.getText().equals("") || tfTelp.getText().equals("")) {
         JOptionPane.showMessageDialog(null, "Lengkapi Data Yang Kosong..!",
                    "Error",JOptionPane.WARNING_MESSAGE);
     }else{
     //Menambahkan data ke dalam row
        DefaultTableModel model = (DefaultTableModel) tbbukualamat.getModel();
         model.addRow(new Object[] {nama, alamat, jenisKelamin, status, noTelp});
         JOptionPane.showMessageDialog(null, "Data Berhasil Ditambahkan");
         
         
     //Membersihkan field setelah data berhasil terinput
        tfNama.setText("");
        tfAlamat.setText("");
        cmbJenisKelamin.setSelectedIndex(0);
        cmbStatus.setSelectedIndex(0);
        tfTelp.setText("");
     } 
    }//GEN-LAST:event_bttambahActionPerformed

    private void bthapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bthapusActionPerformed
            // Cek apakah ada baris yang dipilih
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Pilih baris yang akan dihapus", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Konfirmasi pengguna untuk menghapus data
        int option = JOptionPane.showConfirmDialog(this, "Anda yakin ingin menghapus data ini?", "Konfirmasi", JOptionPane.YES_NO_OPTION);
        if (option == JOptionPane.YES_OPTION) {
            // Hapus data pada baris yang dipilih
            DefaultTableModel model = (DefaultTableModel) tbbukualamat.getModel();
            model.removeRow(selectedRow);

            // Bersihkan input field setelah data dihapus
            tfNama.setText("");
            tfAlamat.setText("");
            cmbJenisKelamin.setSelectedIndex(0);
            cmbStatus.setSelectedIndex(0);
            tfTelp.setText("");

            // Reset pemilihan baris pada tabel
            tbbukualamat.clearSelection();

            // Reset variabel selectedRow
            selectedRow = -1;
            
            // Mengembalikan ke mode tambah dan mengaktifkan kembali tombol tambah  
            isEditMode = false;
            bttambah.setEnabled(true);
            
             // Tampilkan JOptionPane untuk memberi tahu bahwa data berhasil dihapus
             JOptionPane.showMessageDialog(this, "Data berhasil dihapus", "Sukses", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_bthapusActionPerformed

    private void tbbukualamatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbbukualamatMouseClicked
        // Mendapatkan baris yang dipilih saat mouse di-klik pada tabel
         selectedRow = tbbukualamat.getSelectedRow();

        // Menampilkan data dari baris yang dipilih di TextField
        if (selectedRow != -1) {
            DefaultTableModel model = (DefaultTableModel) tbbukualamat.getModel();
            tfNama.setText(model.getValueAt(selectedRow, 0).toString());
            tfAlamat.setText(model.getValueAt(selectedRow, 1).toString());
            cmbJenisKelamin.setSelectedItem(model.getValueAt(selectedRow, 2).toString());
            cmbStatus.setSelectedItem(model.getValueAt(selectedRow, 3).toString());
            tfTelp.setText(model.getValueAt(selectedRow, 4).toString());

            // Mengaktifkan mode edit dan menonaktifkan tombol tambah
            isEditMode = true;
            bttambah.setEnabled(false);
        }
    }//GEN-LAST:event_tbbukualamatMouseClicked

    private void btubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btubahActionPerformed
          // Cek apakah ada baris yang dipilih
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Pilih baris yang akan diedit", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Ambil nilai dari input fields
        String nama = tfNama.getText();
        String alamat= tfAlamat.getText();
        String JenisKelamin = cmbJenisKelamin.getSelectedItem().toString();
        String Status = cmbStatus.getSelectedItem().toString();
        String NoTelp = tfTelp.getText();

        // Validasi input kosong
        if (nama.isEmpty() || alamat.isEmpty() || NoTelp.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Harap lengkapi semua field", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        // Validasi nomor telepon tidak boleh sama dengan nomor telepon lain pada tabel
        DefaultTableModel model = (DefaultTableModel) tbbukualamat.getModel();
        for (int row = 0; row < model.getRowCount(); row++) {
        if (row != selectedRow && NoTelp.equals(model.getValueAt(row, 1).toString())) {
            JOptionPane.showMessageDialog(this, "Nomor telepon sudah ada", "Error", JOptionPane.ERROR_MESSAGE);
            return;
            }
        }
        
        // Update data pada baris yang dipilih
        model.setValueAt(nama, selectedRow, 0);
        model.setValueAt(alamat, selectedRow, 1);
        model.setValueAt(JenisKelamin, selectedRow, 2);
        model.setValueAt(Status, selectedRow, 3);
        model.setValueAt(NoTelp, selectedRow, 4);

        // Bersihkan input field setelah data diubah
        tfNama.setText("");
        tfAlamat.setText("");
        cmbJenisKelamin.setSelectedIndex(0);
        cmbStatus.setSelectedIndex(0);
        tfTelp.setText("");

        // Reset pemilihan baris pada tabel
        tbbukualamat.clearSelection();

        // Mengembalikan ke mode tambah dan mengaktifkan kembali tombol tambah
        isEditMode = false;
        bttambah.setEnabled(true);
        
        // Tampilkan JOptionPane untuk memberi tahu bahwa data berhasil diubah
        JOptionPane.showMessageDialog(this, "Data berhasil diubah", "Sukses", JOptionPane.INFORMATION_MESSAGE);
                                        

    }//GEN-LAST:event_btubahActionPerformed

    private void tbimportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbimportActionPerformed
       // Import File     
        String filePath = "DataBukuAlamat.ext";
        File file = new File(filePath);
        try{
            FileReader fr = new FileReader(file);
            BufferedReader br = new BufferedReader(fr);
            
        DefaultTableModel model = (DefaultTableModel) tbbukualamat.getModel(); 
        Object[] lines = br.lines().toArray();
        
        for(int i = 0; i < lines.length; i++ ){
            String[] row = lines[i].toString().split("/ ");
            model.addRow(row);
        }            
        JOptionPane.showMessageDialog(null, "Berhasil mengimport data");
            
        }catch (Exception e){
            System.err.println("Error: "+e.getMessage());
        }
    }//GEN-LAST:event_tbimportActionPerformed

    private void tbexportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbexportActionPerformed
      // Eksport File
        try{
            BufferedWriter out = new BufferedWriter (new FileWriter("DataBukuAlamat.ext"));
            
            for(int i = 0; i < tbbukualamat.getRowCount(); i++){ // rows
                for (int j = 0; j < tbbukualamat.getColumnCount(); j++){ // columns
                    out.write(tbbukualamat.getValueAt(i, j).toString()+"/ ");
                }
                out.newLine();
            }            
            JOptionPane.showMessageDialog(null, "Berhasil Diexport dalam File");
            
            out.close();
        }catch (Exception e){
            System.err.println("Error: "+e.getMessage());
        }
                
    }//GEN-LAST:event_tbexportActionPerformed

    private void btlaporanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btlaporanActionPerformed
 //Header Laporan
        TextArealaporan.setText(TextArealaporan.getText() + "===================================\n");
        TextArealaporan.setText(TextArealaporan.getText() + "                 LAPORAN                \n");
        TextArealaporan.setFont(TextArealaporan.getFont().deriveFont(Font.BOLD, 14f));
        TextArealaporan.setText(TextArealaporan.getText() + "===================================\n");
        // Laporan
        DefaultTableModel model = (DefaultTableModel) tbbukualamat.getModel();
        int nRow = model.getRowCount(), nCol = model.getColumnCount();
        Object[][] tableData = new Object[nRow][nCol];
            for (int i = 0; i < nRow; i++) {
                for (int j = 0; j < nCol; j++) {
                tableData[i][j] = model.getValueAt(i, j);
            TextArealaporan.append(String.valueOf(tableData[i][j]) + " ");
            }
        TextArealaporan.append("\n");
      }
    }//GEN-LAST:event_btlaporanActionPerformed

    private void btexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btexitActionPerformed
       //Keluar Form
              int keluar = JOptionPane.showConfirmDialog(null, "Apakah Anda yakin ingin keluar?", "Konfirmasi", JOptionPane.YES_NO_OPTION);
                if (keluar == JOptionPane.YES_OPTION) {
                    System.exit(0);
                }
    }//GEN-LAST:event_btexitActionPerformed

    public void showDate(){
        Date d = new Date();
        SimpleDateFormat s = new SimpleDateFormat("dd-MM-yyyy");
        String date = s.format(d);
        DATE.setText(date);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AplikasiBukuAlamat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AplikasiBukuAlamat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AplikasiBukuAlamat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AplikasiBukuAlamat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AplikasiBukuAlamat().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DATE;
    private java.awt.TextArea TextArealaporan;
    private javax.swing.JButton btexit;
    private javax.swing.JButton bthapus;
    private java.awt.Button btlaporan;
    private javax.swing.JButton bttambah;
    private javax.swing.JButton btubah;
    private javax.swing.JComboBox<String> cmbJenisKelamin;
    private javax.swing.JComboBox<String> cmbStatus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panelUtama;
    private javax.swing.JTable tbbukualamat;
    private javax.swing.JButton tbexport;
    private javax.swing.JButton tbimport;
    private javax.swing.JTextField tfAlamat;
    private javax.swing.JTextField tfNama;
    private javax.swing.JTextField tfTelp;
    // End of variables declaration//GEN-END:variables
}
